"""add harvest table

Revision ID: 8500a4ed8aee
Revises: 11431bd64a9f
Create Date: 2025-05-06 09:50:51.509762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8500a4ed8aee'
down_revision = '11431bd64a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('harvest_date', sa.Date(), nullable=False),
    sa.Column('yield_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('harvests')
    # ### end Alembic commands ###
