"""Added indexes to foreign key columns

Revision ID: c8168dbed68d
Revises: 8500a4ed8aee
Create Date: 2025-05-06 10:00:22.549216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8168dbed68d'
down_revision = '8500a4ed8aee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gardens', schema=None) as batch_op:
        batch_op.create_index('idx_garden_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_index('idx_plant_garden_id', ['garden_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_index('idx_plant_garden_id')

    with op.batch_alter_table('gardens', schema=None) as batch_op:
        batch_op.drop_index('idx_garden_user_id')

    # ### end Alembic commands ###
